services:
  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    env_file:
      - .env
    networks:
      - inception
    ports:
      - 9000:9000
    volumes:  
      - wordpress:/var/www/html
    depends_on:
     - mariadb
    restart: always

  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - 443:443
    networks:
      - inception
    volumes:  
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    restart: always

  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    env_file:
      - .env
    networks:
      - inception
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql
    restart: always


networks:
  inception:
    driver: bridge


volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/brheaume/data/db

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/brheaume/data/wp
