services:
  wordpress:
    container_name: wordpress
    image: wordpress_img
    build: requirements/wordpress/
    networks:
      - inception
    volumes:  
      - wordpress:/var/www/html
    depends_on:
     - mariadb
    restart: always

  nginx:
    container_name: nginx
    image: nginx_img
    build: requirements/nginx/
    ports:
      - "443:443"
    networks:
      - inception
    volumes:  
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    restart: always

  mariadb:
    container_name: mariadb
    image: mariadb_img
    build: requirements/mariadb/
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    restart: always


networks:
  inception:
    name: inception


volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/db

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wp
